In [ ]:
import numpy as np
import pandas as pd

In [ ]:
cric_data = np.loadtxt("cric_data.tsv")

ValueError: ignored

In [ ]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)
cric_data


array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  85.,  12., 224.],
       [ 10.,  18.,  63., 161.],
       [ 11.,   4., 107., 276.],
       [ 12.,   7.,  76., 283.],
       [ 13.,  37.,   4., 297.],
       [ 14.,  14.,   5., 139.],
       [ 15.,   0.,  33., 224.],
       [ 16.,   4.,   7., 178.],
       [ 17.,   0.,   0.,   0.],
       [ 18.,  21.,  36., 193.],
       [ 19.,   1.,  66., 231.],
       [ 20.,  62.,   0., 134.],
       [ 21.,   0., 123., 246.],
       [ 22., 138.,  39., 299.],
       [ 23.,  38.,   9., 242.],
       [ 24.,   2.,  11., 214.],
       [ 25.,  46.,  14., 152.],
       [ 26.,  65.,   0., 104.],
       [ 27.,   0.,   0.,   4.],
       [ 28.,  39.,  26., 155.],
       [ 29.,  48.,   4., 168.],
       [ 3

In [ ]:
cric_data.shape

(225, 4)

Question 1: Find the mean, median for Sachin, Rahul, India

In [ ]:
cric_data = cric_data[:, [1, 2, 3]]

In [ ]:
cric_data.shape

(225, 3)

In [ ]:
sachin = cric_data[:, 0]
rahul = cric_data[:, 1]
india = cric_data[:, 2]

In [ ]:
sachin.shape

(225,)

In [ ]:
def stats(col):
  print('Mean', np.mean(col))
  print('Median', np.median(col))

In [ ]:
stats(sachin)

Mean 39.87555555555556
Median 27.0


In [ ]:
stats(rahul)

Mean 32.062222222222225
Median 22.0


In [ ]:
stats(india)

Mean 220.79555555555555
Median 216.0


In [ ]:
np.mean(cric_data, axis=0)
        

array([ 39.87555556,  32.06222222, 220.79555556])

### Question 2: Find histogram of Sachin's scores with 10 bins

In [ ]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

Question 3: find mean of sachin's scores grouped by 25 matches

In [ ]:
sachin25 = sachin.reshape(9, 25)

In [ ]:
sachin25.shape

(9, 25)

In [ ]:
np.mean(sachin25, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

Question 4: Find mean of Sachin's scores where he has scored a century

In [ ]:
sachin >= 100

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
np.mean(sachin[sachin>=100])

125.0

Question 5: Find mean of Sachin's scores when Rahul has scored less than 10

In [ ]:
np.mean(sachin[rahul<10])

40.74285714285714